version: "3"
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: nginx_server
    ports:
      - "3050:80"
  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: backend_server
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "5000:5000"
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: frontend_server
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - api
